<b>Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.</b>

In [4]:
import numpy as np
list=eval(input("Enter a list :"))
N=int(input("Enter number of columns :"))
def Vander(l,n):
    arr=np.array(l)#Converting a list to array
    return np.vander(arr,n,increasing=False)# When increasing order is False

Vander(list,N)# Calling the function

Enter a list :[1,2,3,4,5,6]
Enter number of columns :3


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1],
       [36,  6,  1]])

In [5]:
import numpy as np
list=eval(input("Enter a list :"))
N=int(input("Enter number of columns :"))
def Vander(l,n):
    arr=np.array(l)#Converting a list to array
    return np.vander(arr,n,increasing=True)#When Increasing order is True

Vander(list,N)# Calling the function

Enter a list :[1,2,3,4,5,6,7,8,9,10]
Enter number of columns :5


array([[    1,     1,     1,     1,     1],
       [    1,     2,     4,     8,    16],
       [    1,     3,     9,    27,    81],
       [    1,     4,    16,    64,   256],
       [    1,     5,    25,   125,   625],
       [    1,     6,    36,   216,  1296],
       [    1,     7,    49,   343,  2401],
       [    1,     8,    64,   512,  4096],
       [    1,     9,    81,   729,  6561],
       [    1,    10,   100,  1000, 10000]])

### Alternative method

In [10]:
list=eval(input("Enter a list :"))
N=int(input("Enter number of columns :"))
def Vander(l,n):
    arr=np.array(l)#Converting a list to array
    return np.column_stack([arr**(N-1-i) for i in range(N)])

Vander(list,N)# Calling the function



Enter a list :[1,2,3,4,5]
Enter number of columns :3


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]], dtype=int32)

<b>Task2:Write a function to find moving average in an array over a window:
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.</b>

In [ ]:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10
===== == == == == == == == == == ==
Input 10 20 30 40 50 60 70 80 90 100
y1 25 = (10+20+30+40)/4
y2 35 = (20+30+40+50)/4
y3 45 = (30+40+50+60)/4
y4 55 = (40+50+60+70)/4
y5 65 = (50+60+70+80)/4
y6 75 = (60+70+80+90)/4
y7 85 = (70+80+90+100)/4
Thus, the moving average sequence has n-k+1=10-4+1=7 values.

In [61]:
Sequence=eval(input("Enter a sequence(list or tuple) :"))
Window_size=int(input("Enter Window size :"))
Moving_avg_list=[]
def moving_avg(sequence,windowsize):
    i=1
    
    while i<=len(sequence)-windowsize+1 :
        mov_avg=0
        cnt=0
        for j in range(i-1,len(sequence)):
            cnt=cnt+1
            if cnt==windowsize+1:
                break
            else:
                mov_avg=mov_avg+(sequence[j])
        result=int(mov_avg/windowsize)
        Moving_avg_list.append(result)
        i=i+1
    print("The Moving Avg is :",Moving_avg_list)
            
moving_avg(Sequence,Window_size)

    

Enter a sequence(list or tuple) :[10,20,30,40,50,60,70,80,90,100]
Enter Window size :4
The Moving Avg is : [25, 35, 45, 55, 65, 75, 85]


### Testing with [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and size=3

In [62]:
Sequence=eval(input("Enter a sequence(list or tuple) :"))
Window_size=int(input("Enter Window size :"))
Moving_avg_list=[]
def moving_avg(sequence,windowsize):
    i=1
    
    while i<=len(sequence)-windowsize+1 :
        mov_avg=0
        cnt=0
        for j in range(i-1,len(sequence)):
            cnt=cnt+1
            if cnt==windowsize+1:
                break
            else:
                mov_avg=mov_avg+(sequence[j])
        result=int(mov_avg/windowsize)
        Moving_avg_list.append(result)
        i=i+1
    print("The Moving Avg is :",Moving_avg_list)
            
moving_avg(Sequence,Window_size)

    

Enter a sequence(list or tuple) :[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
Enter Window size :3
The Moving Avg is : [5, 4, 5, 6, 9, 28, 49, 72, 84, 93, 116]
